<?xml version="1.0"?>
<package format="3">
  <name>grupo03_kuka_kr6_bringup</name>
  <version>1.0.0</version>
  <description>Launch de visualización para la práctica IMT-342.</description>
  <maintainer email="imt342.robotica@example.com">IMT-342 Robótica</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>kuka_agilus_support</exec_depend>
  <exec_depend>kuka_resources</exec_depend>
  <exec_depend>rmw_cyclonedds_cpp</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
